// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://vkunssec.vercel.app"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/vkunssec/contabius/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar as contas bancárias",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Rota para retornar as contas bancárias",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "678079f6f5080a39a8eedc1e"
                        ],
                        "description": "Ids das contas bancárias a serem retornadas",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain.Accounts"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para criar uma conta bancária",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Rota para criar uma conta bancária",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da conta bancária",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain.Accounts"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest"
                        }
                    }
                }
            }
        },
        "/account/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para deletar uma conta bancária",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Rota para deletar uma conta bancária",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID da conta bancária",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest"
                        }
                    }
                }
            }
        },
        "/account/update/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para atualizar uma conta bancária",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Rota para atualizar uma conta bancária",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da conta bancária",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain.Accounts"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ID da conta bancária",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest"
                        }
                    }
                }
            }
        },
        "/category": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar todas as categorias",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Rota para retornar todas as categorias",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "678079f6f5080a39a8eedc1e"
                        ],
                        "description": "Ids das categorias a serem retornadas",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_handlers_category.GetCategoriesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.InternalServerError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para criar uma categoria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Rota para criar uma categoria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da categoria",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain.Categories"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.InternalServerError"
                        }
                    }
                }
            }
        },
        "/category/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para deletar uma categoria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Rota para deletar uma categoria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID da categoria",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest"
                        }
                    }
                }
            }
        },
        "/category/update/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para atualizar uma categoria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Rota para atualizar uma categoria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da categoria",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain.Categories"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ID da categoria",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest"
                        }
                    }
                }
            }
        },
        "/methods": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar todos os métodos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Methods"
                ],
                "summary": "Rota para retornar todos os métodos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "678079f6f5080a39a8eedc1e"
                        ],
                        "description": "Ids dos métodos a serem retornados",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_handlers_methods.GetMethodsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.InternalServerError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para criar um método",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Methods"
                ],
                "summary": "Rota para criar um método",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados do método",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain.Methods"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.InternalServerError"
                        }
                    }
                }
            }
        },
        "/methods/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para deletar um método",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Methods"
                ],
                "summary": "Rota para deletar um método",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do método",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest"
                        }
                    }
                }
            }
        },
        "/methods/update/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para atualizar um método",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Methods"
                ],
                "summary": "Rota para atualizar um método",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados do método",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain.Methods"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ID do método",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_vkunssec_contabius_pkg_domain.Accounts": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "Nome da conta",
                    "type": "string",
                    "example": "Conta Corrente"
                },
                "color": {
                    "description": "Cor da conta",
                    "type": "string",
                    "example": "#000000"
                },
                "created_at": {
                    "description": "Data de criação",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "description": "ID da conta",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                },
                "updated_at": {
                    "description": "Data de atualização",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                }
            }
        },
        "github_com_vkunssec_contabius_pkg_domain.Categories": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Nome da categoria",
                    "type": "string",
                    "example": "Alimentação"
                },
                "created_at": {
                    "description": "Data de criação",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "description": "ID da categoria",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                },
                "parent": {
                    "description": "ID do pai da categoria",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                },
                "updated_at": {
                    "description": "Data de atualização",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                }
            }
        },
        "github_com_vkunssec_contabius_pkg_domain.Method": {
            "type": "string",
            "enum": [
                "credit",
                "debit",
                "pix",
                "boleto",
                "cash"
            ],
            "x-enum-varnames": [
                "MethodCredit",
                "MethodDebit",
                "MethodPix",
                "MethodBoleto",
                "MethodCash"
            ]
        },
        "github_com_vkunssec_contabius_pkg_domain.Methods": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Data de criação",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "description": "ID do método de pagamento",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                },
                "method": {
                    "description": "Método de pagamento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain.Method"
                        }
                    ],
                    "example": "credit"
                },
                "updated_at": {
                    "description": "Data de atualização",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                }
            }
        },
        "github_com_vkunssec_contabius_pkg_domain_common.BadRequest": {
            "description": "Estrutura padrão de resposta de erro de requisição",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Mensagem descritiva",
                    "type": "string",
                    "example": "Erro ao processar a requisição"
                },
                "success": {
                    "description": "Indica se a operação foi bem sucedida",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_vkunssec_contabius_pkg_domain_common.InternalServerError": {
            "description": "Estrutura padrão de resposta de erro de servidor interno",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Mensagem descritiva",
                    "type": "string",
                    "example": "Internal Server Error"
                },
                "success": {
                    "description": "Indica se a operação foi bem sucedida",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_vkunssec_contabius_pkg_domain_common.Response": {
            "description": "Estrutura padrão de resposta",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Dados da resposta"
                },
                "message": {
                    "description": "Mensagem descritiva",
                    "type": "string",
                    "example": "Operação realizada com sucesso"
                },
                "success": {
                    "description": "Indica se a operação foi bem sucedida",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "pkg_handlers_category.GetCategoriesResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "description": "Dados das categorias",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain.Categories"
                    }
                },
                "message": {
                    "description": "Mensagem de sucesso ou erro",
                    "type": "string",
                    "example": "Categorias retornadas com sucesso"
                },
                "success": {
                    "description": "Sucesso da operação",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "pkg_handlers_methods.GetMethodsResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Mensagem de sucesso ou erro",
                    "type": "string",
                    "example": "Métodos retornados com sucesso"
                },
                "methods": {
                    "description": "Dados dos métodos",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_vkunssec_contabius_pkg_domain.Methods"
                    }
                },
                "success": {
                    "description": "Sucesso da operação",
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Bearer token authentication",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "${HOST}",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Contabius API",
	Description:      "API para gerenciamento de gastos e informações financeiras",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
