// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://vkunssec.vercel.app"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/vkunssec/contabius/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar as contas bancárias",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Rota para retornar as contas bancárias",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "678079f6f5080a39a8eedc1e"
                        ],
                        "description": "Ids das contas bancárias a serem retornadas",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Accounts"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para criar uma conta bancária",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Rota para criar uma conta bancária",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da conta bancária",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/account/remove/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para deletar uma conta bancária",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Rota para deletar uma conta bancária",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID da conta bancária",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/account/update/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para atualizar uma conta bancária",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Rota para atualizar uma conta bancária",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da conta bancária",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Accounts"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ID da conta bancária",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/category": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar todas as categorias",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Rota para retornar todas as categorias",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "678079f6f5080a39a8eedc1e"
                        ],
                        "description": "Ids das categorias a serem retornadas",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetCategoriesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para criar uma categoria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Rota para criar uma categoria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da categoria",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerError"
                        }
                    }
                }
            }
        },
        "/category/remove/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para deletar uma categoria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Rota para deletar uma categoria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID da categoria",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/category/update/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para atualizar uma categoria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Rota para atualizar uma categoria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da categoria",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Categories"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ID da categoria",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/costs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar os custos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Costs"
                ],
                "summary": "Rota para retornar os custos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "678079f6f5080a39a8eedc1e"
                        ],
                        "description": "Ids dos custos a serem retornados",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Costs"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para criar um custo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Costs"
                ],
                "summary": "Rota para criar um custo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados do custo",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/costs/remove/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para deletar um custo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Costs"
                ],
                "summary": "Rota para deletar um custo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do custo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/costs/update/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para atualizar um custo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Costs"
                ],
                "summary": "Rota para atualizar um custo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados do custo",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Costs"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ID do custo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/investment/update/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para atualizar um investimento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investments"
                ],
                "summary": "Rota para atualizar um investimento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados do investimento",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Investments"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ID do investimento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/investments": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar os investimentos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investments"
                ],
                "summary": "Rota para retornar os investimentos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10,
                                11,
                                12,
                                13,
                                14,
                                15
                            ],
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            0,
                            1,
                            2,
                            3
                        ],
                        "description": "Ids dos investimentos a serem retornados",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Investments"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para criar um investimento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investments"
                ],
                "summary": "Rota para criar um investimento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados do investimento",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InvestmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/investments/get_types": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar todos os tipos de investimentos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investments"
                ],
                "summary": "Rota para retornar todos os tipos de investimentos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10,
                                11,
                                12,
                                13,
                                14,
                                15
                            ],
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            0,
                            1,
                            2,
                            3
                        ],
                        "description": "Ids dos investimentos a serem retornados",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetInvestmentsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerError"
                        }
                    }
                }
            }
        },
        "/investments/remove/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para deletar um investimento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investments"
                ],
                "summary": "Rota para deletar um investimento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do investimento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/methods": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar todos os métodos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Methods"
                ],
                "summary": "Rota para retornar todos os métodos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                0,
                                1,
                                2,
                                3,
                                4
                            ],
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            0,
                            1,
                            2,
                            3
                        ],
                        "description": "Ids dos métodos a serem retornados",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetMethodsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/InternalServerError"
                        }
                    }
                }
            }
        },
        "/revenues": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar as receitas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Revenues"
                ],
                "summary": "Rota para retornar as receitas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "678079f6f5080a39a8eedc1e"
                        ],
                        "description": "Ids das receitas a serem retornadas",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Revenues"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para criar uma receita",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Revenues"
                ],
                "summary": "Rota para criar uma receita",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da receita",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/RevenueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/revenues/remove/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para deletar uma receita",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Revenues"
                ],
                "summary": "Rota para deletar uma receita",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID da receita",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/revenues/update/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para atualizar uma receita",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Revenues"
                ],
                "summary": "Rota para atualizar uma receita",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da receita",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Revenues"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ID da receita",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para logar um usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Rota para logar um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/user/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para retornar o usuário logado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Rota para retornar o usuário logado",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para criar um usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Rota para criar um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/user/update/password/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para atualizar a senha de um usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Rota para atualizar a senha de um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da senha",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserUpdatePassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        },
        "/user/update/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Rota para atualizar um usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Rota para atualizar um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserUpdateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/BadRequest"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AccountRequest": {
            "type": "object",
            "required": [
                "account",
                "color"
            ],
            "properties": {
                "account": {
                    "description": "Nome da conta",
                    "type": "string",
                    "example": "Conta Corrente"
                },
                "color": {
                    "description": "Cor da conta",
                    "type": "string",
                    "example": "#000000"
                }
            }
        },
        "Accounts": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "Nome da conta",
                    "type": "string",
                    "example": "Conta Corrente"
                },
                "color": {
                    "description": "Cor da conta",
                    "type": "string",
                    "example": "#000000"
                },
                "created_at": {
                    "description": "Data de criação",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "description": "ID da conta",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                },
                "updated_at": {
                    "description": "Data de atualização",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                }
            }
        },
        "BadRequest": {
            "description": "Estrutura padrão de resposta de erro de requisição",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Mensagem descritiva",
                    "type": "string",
                    "example": "Erro ao processar a requisição"
                },
                "success": {
                    "description": "Indica se a operação foi bem sucedida",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "Categories": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Nome da categoria",
                    "type": "string",
                    "example": "Alimentação"
                },
                "created_at": {
                    "description": "Data de criação",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "description": "ID da categoria",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                },
                "parent": {
                    "description": "ID do pai da categoria",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                },
                "updated_at": {
                    "description": "Data de atualização",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                }
            }
        },
        "CategoryRequest": {
            "type": "object",
            "required": [
                "category"
            ],
            "properties": {
                "category": {
                    "description": "Nome da categoria",
                    "type": "string",
                    "example": "Alimentação"
                },
                "parent": {
                    "description": "ID do pai da categoria",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                }
            }
        },
        "CostRequest": {
            "type": "object",
            "required": [
                "amount",
                "category",
                "cost"
            ],
            "properties": {
                "amount": {
                    "description": "Valor do custo",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Money"
                        }
                    ]
                },
                "category": {
                    "description": "ID da categoria",
                    "allOf": [
                        {
                            "$ref": "#/definitions/PartialCategoryRequest"
                        }
                    ]
                },
                "cost": {
                    "description": "Descrição do custo",
                    "type": "string",
                    "example": "aluguel"
                },
                "installments": {
                    "description": "Número de parcelas",
                    "type": "integer",
                    "example": 12
                },
                "methods": {
                    "description": "Método de pagamento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Methods"
                        }
                    ]
                }
            }
        },
        "Costs": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Valor do custo",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Money"
                        }
                    ]
                },
                "category": {
                    "description": "Categoria do custo",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Categories"
                        }
                    ]
                },
                "cost": {
                    "description": "Descrição do custo",
                    "type": "string",
                    "example": "aluguel"
                },
                "created_at": {
                    "description": "Data de criação do custo",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "description": "ID do custo",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                },
                "installments": {
                    "description": "Número de parcelas",
                    "type": "integer",
                    "example": 12
                },
                "methods": {
                    "description": "Método de pagamento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Methods"
                        }
                    ]
                },
                "updated_at": {
                    "description": "Data de atualização do custo",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                }
            }
        },
        "Currency": {
            "type": "string",
            "enum": [
                "BRL",
                "USD",
                "EUR"
            ],
            "x-enum-varnames": [
                "CurrencyBRL",
                "CurrencyUSD",
                "CurrencyEUR"
            ]
        },
        "GetCategoriesResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "description": "Dados das categorias",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Categories"
                    }
                },
                "message": {
                    "description": "Mensagem de sucesso ou erro",
                    "type": "string",
                    "example": "Categorias retornadas com sucesso"
                },
                "success": {
                    "description": "Sucesso da operação",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "GetInvestmentsResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Mensagem de sucesso ou erro",
                    "type": "string",
                    "example": "Investimentos retornados com sucesso"
                },
                "success": {
                    "description": "Sucesso da operação",
                    "type": "boolean",
                    "example": true
                },
                "types": {
                    "description": "Dados dos investimentos",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/InvestmentType"
                    }
                }
            }
        },
        "GetMethodsResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Mensagem de sucesso ou erro",
                    "type": "string",
                    "example": "Métodos retornados com sucesso"
                },
                "methods": {
                    "description": "Dados dos métodos",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Methods"
                    }
                },
                "success": {
                    "description": "Sucesso da operação",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "InternalServerError": {
            "description": "Estrutura padrão de resposta de erro de servidor interno",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Mensagem descritiva",
                    "type": "string",
                    "example": "Internal Server Error"
                },
                "success": {
                    "description": "Indica se a operação foi bem sucedida",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "InvestmentId": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15
            ],
            "x-enum-varnames": [
                "InvestmentTypeCDIId",
                "InvestmentTypeCDBId",
                "InvestmentTypeLCAId",
                "InvestmentTypeLCIId",
                "InvestmentTypePoupancaId",
                "InvestmentTypeTesouroDiretoId",
                "InvestmentTypeFundosInvestimentoId",
                "InvestmentTypeAcoesId",
                "InvestmentTypeFIIsId",
                "InvestmentTypeCRIId",
                "InvestmentTypeCRAId",
                "InvestmentTypeDebenturesId",
                "InvestmentTypeBDRId",
                "InvestmentTypeCOEId",
                "InvestmentTypeOtherId"
            ]
        },
        "InvestmentLiteral": {
            "type": "string",
            "enum": [
                "cdi",
                "cdb",
                "lca",
                "lci",
                "poupanca",
                "tesouro_direto",
                "fundos_investimento",
                "acoes",
                "fiis",
                "cri",
                "cra",
                "debentures",
                "bdr",
                "coe",
                "other"
            ],
            "x-enum-comments": {
                "InvestmentTypeAcoes": "Ações",
                "InvestmentTypeBDR": "Depositário Brasileiro de Recebíveis",
                "InvestmentTypeCDB": "Certificado de Depósito Bancário",
                "InvestmentTypeCDI": "Certificado de Depósito Interbancário",
                "InvestmentTypeCOE": "Certificado de Operações Estruturadas",
                "InvestmentTypeCRA": "Certificado de Recebíveis do Agronegócio",
                "InvestmentTypeCRI": "Certificado de Recebíveis Imobiliários",
                "InvestmentTypeDebentures": "Debêntures",
                "InvestmentTypeFIIs": "Fundos de Investimento Imobiliário",
                "InvestmentTypeFundosInvestimento": "Fundos de Investimento",
                "InvestmentTypeLCA": "Letra de Crédito do Agronegócio",
                "InvestmentTypeLCI": "Letra de Crédito Imobiliário",
                "InvestmentTypeOther": "Outros",
                "InvestmentTypePoupanca": "Poupança",
                "InvestmentTypeTesouroDireto": "Tesouro Direto"
            },
            "x-enum-varnames": [
                "InvestmentTypeCDI",
                "InvestmentTypeCDB",
                "InvestmentTypeLCA",
                "InvestmentTypeLCI",
                "InvestmentTypePoupanca",
                "InvestmentTypeTesouroDireto",
                "InvestmentTypeFundosInvestimento",
                "InvestmentTypeAcoes",
                "InvestmentTypeFIIs",
                "InvestmentTypeCRI",
                "InvestmentTypeCRA",
                "InvestmentTypeDebentures",
                "InvestmentTypeBDR",
                "InvestmentTypeCOE",
                "InvestmentTypeOther"
            ]
        },
        "InvestmentRequest": {
            "type": "object",
            "required": [
                "account",
                "amount",
                "investment_type"
            ],
            "properties": {
                "account": {
                    "description": "Conta do usuário",
                    "allOf": [
                        {
                            "$ref": "#/definitions/PartialAccountRequest"
                        }
                    ]
                },
                "amount": {
                    "description": "Valor do investimento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Money"
                        }
                    ]
                },
                "description": {
                    "description": "Descrição do investimento",
                    "type": "string",
                    "example": "Investimento em CDB"
                },
                "investment_type": {
                    "description": "Tipo de investimento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/InvestmentType"
                        }
                    ]
                },
                "recurrence": {
                    "description": "Recurrence do investimento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Recurrence"
                        }
                    ]
                },
                "recurrence_day": {
                    "description": "Dia da recorrência",
                    "type": "integer"
                }
            }
        },
        "InvestmentType": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID do investimento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/InvestmentId"
                        }
                    ],
                    "example": 1
                },
                "investment": {
                    "description": "Tipo de investimento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/InvestmentLiteral"
                        }
                    ],
                    "example": "cdi"
                }
            }
        },
        "Investments": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "Conta do usuário",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Accounts"
                        }
                    ]
                },
                "amount": {
                    "description": "Valor do investimento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Money"
                        }
                    ]
                },
                "created_at": {
                    "description": "Data de criação do investimento",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "description": {
                    "description": "Descrição do investimento",
                    "type": "string",
                    "example": "Investimento em CDB"
                },
                "id": {
                    "description": "ID do investimento",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                },
                "investment_type": {
                    "description": "Tipo de investimento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/InvestmentType"
                        }
                    ]
                },
                "recurrence": {
                    "description": "Recurrence do investimento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Recurrence"
                        }
                    ],
                    "example": "monthly"
                },
                "recurrence_day": {
                    "description": "Dia da recorrência",
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "description": "Data de atualização do investimento",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                }
            }
        },
        "Method": {
            "type": "string",
            "enum": [
                "credit",
                "debit",
                "pix",
                "boleto",
                "cash"
            ],
            "x-enum-varnames": [
                "MethodCredit",
                "MethodDebit",
                "MethodPix",
                "MethodBoleto",
                "MethodCash"
            ]
        },
        "MethodId": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "MethodCreditId",
                "MethodDebitId",
                "MethodPixId",
                "MethodBoletoId",
                "MethodCashId"
            ]
        },
        "Methods": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID do método de pagamento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/MethodId"
                        }
                    ],
                    "example": 1
                },
                "method": {
                    "description": "Método de pagamento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Method"
                        }
                    ],
                    "example": "credit"
                }
            }
        },
        "Money": {
            "type": "object",
            "properties": {
                "currency": {
                    "description": "default code BRL",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Currency"
                        }
                    ],
                    "example": "BRL"
                },
                "quantity": {
                    "type": "integer",
                    "example": 1000
                }
            }
        },
        "PartialAccountRequest": {
            "type": "object",
            "required": [
                "account",
                "color",
                "id"
            ],
            "properties": {
                "account": {
                    "description": "Nome da conta",
                    "type": "string",
                    "example": "Conta Corrente"
                },
                "color": {
                    "description": "Cor da conta",
                    "type": "string",
                    "example": "#000000"
                },
                "id": {
                    "description": "ID da conta",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                }
            }
        },
        "PartialCategoryRequest": {
            "type": "object",
            "required": [
                "category",
                "id"
            ],
            "properties": {
                "category": {
                    "description": "Nome da categoria",
                    "type": "string",
                    "example": "Alimentação"
                },
                "id": {
                    "description": "ID da categoria",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                }
            }
        },
        "Recurrence": {
            "type": "string",
            "enum": [
                "monthly",
                "yearly",
                "sporadic"
            ],
            "x-enum-comments": {
                "RecurrenceMonthly": "Mensal",
                "RecurrenceSporadic": "Esporádico",
                "RecurrenceYearly": "Anual"
            },
            "x-enum-varnames": [
                "RecurrenceMonthly",
                "RecurrenceYearly",
                "RecurrenceSporadic"
            ]
        },
        "Response": {
            "description": "Estrutura padrão de resposta",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Dados da resposta"
                },
                "message": {
                    "description": "Mensagem descritiva",
                    "type": "string",
                    "example": "Operação realizada com sucesso"
                },
                "success": {
                    "description": "Indica se a operação foi bem sucedida",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "RevenueRequest": {
            "type": "object",
            "required": [
                "amount",
                "revenue"
            ],
            "properties": {
                "amount": {
                    "description": "Valor da receita",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Money"
                        }
                    ]
                },
                "method": {
                    "description": "Método de pagamento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Methods"
                        }
                    ]
                },
                "revenue": {
                    "description": "Receita",
                    "type": "string",
                    "example": "salário"
                }
            }
        },
        "Revenues": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Valor da receita",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Money"
                        }
                    ]
                },
                "created_at": {
                    "description": "Data de criação da receita",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "description": "ID da receita",
                    "type": "string",
                    "example": "678079f6f5080a39a8eedc1e"
                },
                "method": {
                    "description": "Método de pagamento",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Methods"
                        }
                    ]
                },
                "revenue": {
                    "description": "Receita",
                    "type": "string",
                    "example": "salário"
                },
                "updated_at": {
                    "description": "Data de atualização da receita",
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                }
            }
        },
        "UserLogin": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "Email do usuário",
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "description": "Senha do usuário",
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "UserRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "type"
            ],
            "properties": {
                "email": {
                    "description": "Email do usuário",
                    "type": "string",
                    "example": "user@example.com"
                },
                "name": {
                    "description": "Nome do usuário",
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "description": "Senha do usuário",
                    "type": "string",
                    "example": "password123"
                },
                "type": {
                    "description": "Tipo de usuário",
                    "allOf": [
                        {
                            "$ref": "#/definitions/UserType"
                        }
                    ],
                    "example": "admin"
                }
            }
        },
        "UserType": {
            "type": "string",
            "enum": [
                "admin",
                "user",
                "guest"
            ],
            "x-enum-varnames": [
                "UserTypeAdmin",
                "UserTypeUser",
                "UserTypeGuest"
            ]
        },
        "UserUpdatePassword": {
            "type": "object",
            "required": [
                "password",
                "password_confirm"
            ],
            "properties": {
                "password": {
                    "description": "Senha do usuário",
                    "type": "string",
                    "example": "password123"
                },
                "password_confirm": {
                    "description": "Senha do usuário",
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "UserUpdateRequest": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "description": "Email do usuário",
                    "type": "string",
                    "example": "user@example.com"
                },
                "name": {
                    "description": "Nome do usuário",
                    "type": "string",
                    "example": "John Doe"
                },
                "type": {
                    "description": "Tipo de usuário",
                    "allOf": [
                        {
                            "$ref": "#/definitions/UserType"
                        }
                    ],
                    "example": "admin"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Bearer token authentication",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "${HOST}",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Contabius API",
	Description:      "API para gerenciamento de gastos e informações financeiras",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
