baseURL = 'https://contabius-h7jpgeybda-uc.a.run.app/docs'
languageCode = 'pt-br'
title = 'contabius'
theme = 'hugo-theme-monochrome'

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    author = "vkunssec"
    enable_site_search = true
    color_scheme = "dark"
    footer = "vkunssec ©"
    enable_collapsible_toc = true

[build]
    noJSConfigInAssets = true

[[menu.navbar]]
    identifier = "home"
    name = "Página Principal"
    url = "/"
    weight = 1
[[menu.navbar]]
    identifier = "account"
    name = "Contas"
    url = "/account/"
    weight = 2
    [[menu.navbar]]
        identifier = "account_routes"
        name = "Assinatura de Rotas"
        url = "/account/routes/"
        parent = "account"
        weight = 3
