basePath: /
host: ${HOST}
info:
  contact:
    name: API Support
    url: https://vkunssec.vercel.app
  description: API para gerenciamento de contas bancárias
  license:
    name: MIT
    url: https://github.com/vkunssec/contabius/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Contabius API
  version: "1.0"
paths: {}
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    description: Bearer token authentication
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
