basePath: /
definitions:
  github_com_vkunssec_contabius_pkg_domain.Accounts:
    properties:
      account:
        type: string
      color:
        type: string
      created_at:
        type: string
      id:
        type: string
      updated_at:
        type: string
    type: object
  github_com_vkunssec_contabius_pkg_domain_common.BadRequest:
    description: Estrutura padrão de resposta de erro de requisição
    properties:
      message:
        description: Mensagem descritiva
        example: Erro ao processar a requisição
        type: string
      success:
        description: Indica se a operação foi bem sucedida
        example: false
        type: boolean
    type: object
  github_com_vkunssec_contabius_pkg_domain_common.Response:
    description: Estrutura padrão de resposta
    properties:
      data:
        description: Dados da resposta
      message:
        description: Mensagem descritiva
        example: Operação realizada com sucesso
        type: string
      success:
        description: Indica se a operação foi bem sucedida
        example: true
        type: boolean
    type: object
host: ${HOST}
info:
  contact:
    name: API Support
    url: https://vkunssec.vercel.app
  description: API para gerenciamento de gastos e informações financeiras
  license:
    name: MIT
    url: https://github.com/vkunssec/contabius/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Contabius API
  version: "1.0"
paths:
  /account:
    get:
      consumes:
      - application/json
      description: Rota para retornar as contas bancárias
      parameters:
      - description: Token Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - collectionFormat: csv
        description: Ids das contas bancárias a serem retornadas
        example:
        - 678079f6f5080a39a8eedc1e
        in: query
        items:
          type: string
        name: ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_vkunssec_contabius_pkg_domain.Accounts'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest'
      security:
      - ApiKeyAuth: []
      summary: Rota para retornar as contas bancárias
      tags:
      - Account
    post:
      consumes:
      - application/json
      description: Rota para criar uma conta bancária
      parameters:
      - description: Token Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Dados da conta bancária
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_vkunssec_contabius_pkg_domain.Accounts'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest'
      security:
      - ApiKeyAuth: []
      summary: Rota para criar uma conta bancária
      tags:
      - Account
  /account/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Rota para deletar uma conta bancária
      parameters:
      - description: Token Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID da conta bancária
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest'
      security:
      - ApiKeyAuth: []
      summary: Rota para deletar uma conta bancária
      tags:
      - Account
  /account/update/{id}:
    put:
      consumes:
      - application/json
      description: Rota para atualizar uma conta bancária
      parameters:
      - description: Token Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Dados da conta bancária
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_vkunssec_contabius_pkg_domain.Accounts'
      - description: ID da conta bancária
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_vkunssec_contabius_pkg_domain_common.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_vkunssec_contabius_pkg_domain_common.BadRequest'
      security:
      - ApiKeyAuth: []
      summary: Rota para atualizar uma conta bancária
      tags:
      - Account
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    description: Bearer token authentication
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
